config/routes.rb
Rails.application.routes.draw do
  

  resources :pins

  devise_for :users
  get 'sitio/inicio'
  

   root to: 'sitio#inicio'
  get 'users/:id' => 'users#show', as: :user
  get 'users/:id' => 'users#home', as: :home
  get 'acerca' => 'sitio#acerca'
  get 'login' => 'login#login'
  get 'foro', to: 'pins#index', as: :foro

end

app/models/pin.rb
class Pin < ActiveRecord::Base
	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
	validates :description, presence: true
	validates_attachment :image,
						content_type: { content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif']},
						size: { less_than: 5.megabytes }


	belongs_to :user
	#actualizacion oja.la 
	attr_accessible :user_id, :description, :image, :image_remote_url

	
	def image_remote_url=(url_value)
		self.image = URI.parse(url_value) unless url_value.blank?
		super
	end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :pins

  #actualizacion oja.la
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_filter :configure_permitted_parameters, if: :devise_controller?

	protected
		def configure_permitted_parameters
		devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
		devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :current_password, :password, :password_confirmation) }
	end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def login
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_filter :authenticate_user!, except: [:index] #Filtro que valida si esta autenticado
  before_action :set_pin, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @pins = Pin.order("created_at desc").page(params[:page]).per_page(9);
    respond_with(@pins)
  end

  def show
    respond_with(@pin)
  end

  def new
    @pin = current_user.pins.new
    respond_with(@pin)
  end

  def edit
  end

  def create
    @pin = current_user.pins.new(pin_params)
    @pin.save
    respond_with(@pin)
  end

  def update
    @pin.update(pin_params)
    respond_with(@pin)
  end

  def destroy
    @pin.destroy
    respond_with(@pin)
  end

  private
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def pin_params
      params.require(:pin).permit(:description, :image, :image_file_name, :image_remote_url)
    end
  
    def latest
      @pins = Pin.order("created_at desc").limit(5);
      respond_with(@pins)
    end

end

app/controllers/sitio_controller.rb
class SitioController < ApplicationController
  def inicio
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #def show
  #	@user = User.find(params[:id])
  #	@pins = @user.pins.order("created_at desc").page(params[:page]).per_page(9);
  #end

  def show
  	@user = User.find_by_id(params[:id])
  	if @user
  		@pins = @user.pins.order("created_at desc").page(params[:page]).per_page(9);
  		render action: :show
  	else
  		render file: 'public/404', status: 404, formats: [:html]
  	end
  end

  def home(id)
  	@user = User.find(params[:id])
  	return current_user.id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	#agregando metodos para comportamientos visuales
	def flash_class(type)
		case type
		when :alert
			"alert-danger"
		
		when :notice
			"alert-info"
		
		when :warning
			"alert-warning"
		end
	end
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/sitio_helper.rb
module SitioHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_aside.html.erb

<aside style="margin-top: 20px;" class="hidden-xs container col-xs-12 col-sm-4 col-md-4 center-block" id="extra-content">

						<h3 class="text-info"><small><span class="glyphicon glyphicon-star"></span></small> Más popular</h3>
						<ul>
							<a><li>codebots.net</li></a>
							<a><li>andybros.com</li></a>
							<a><li>chachigonzales.com</li></a>
							<a><li>RubinMz.com</li></a>
							<br />
						</ul>

						<section>
							<h3>Últimos artículos</h3>
							<ul>
							<!--% @pins.latest do |pin| %>
								<li><!%= pin.description %></li>
							<!% end %-->
							</ul>
							<p>
							Obtengo de la db los últimos titulos de artículos y un poco de su texto, por quien fue
							creado, la fecha, likes, comentarios, etc...
							</p>
							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
							</p>
							<p>
							Duis aute irure dolor in reprehenderit in voluptate velit esse
							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
							</p>
						</section>


						<script>
							$(document).ready(function(){
								$("#categorias a").each(function(i){
									if(i%2!=0){$(this).addClass("fsPair");}
									else{$(this).addClass("fsNon");}
								});
							});	
						</script>

						<section id="categorias">
							<h3>Contenido por carpetas</h3>
							<p>
							aqui metere alguna estupidez
							</p>
							
						</section>

						<section>
							<h3>Contenido Social</h3>
							<p>
							aqui metere lashlksahkjasasdj
							</p>
							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
							</p>


							<div class="fb-like" data-href="https://www.facebook.com/codebots.net" data-layout="standard" data-action="like" data-show-faces="true" data-share="true" />
								
								<a class="btn btn-block btn-social btn-github" onclick="_gaq.push(['_trackEvent', 'btn-social', 'click', 'btn-github']);">
						            <i class="fa fa-github"></i> Sign in with GitHub
						          </a>

								  <a class="btn btn-block btn-social btn-facebook" onclick="_gaq.push(['_trackEvent', 'btn-social', 'click', 'btn-facebook']);">
						            <i class="fa fa-facebook"></i> Sign in with Facebook
						          </a>

								<a class="btn btn-block btn-social btn-twitter">
								   <i class="fa fa-twitter"></i> Sign in with Twitter
								 </a>
								  <a class="btn btn-block btn-social btn-google-plus" onclick="_gaq.push(['_trackEvent', 'btn-social', 'click', 'btn-google-plus']);">
						            <i class="fa fa-google-plus"></i> Sign in with Google
						          </a>
						          <a class="btn btn-block btn-social btn-instagram" onclick="_gaq.push(['_trackEvent', 'btn-social', 'click', 'btn-instagram']);">
						            <i class="fa fa-instagram"></i> Sign in with Instagram
						          </a>
						           <a class="btn btn-block btn-social btn-tumblr" onclick="_gaq.push(['_trackEvent', 'btn-social', 'click', 'btn-tumblr']);">
						            <i class="fa fa-tumblr"></i> Sign in with Tumblr
						          </a>

						          
						</section>
				</aside>

app/views/layouts/_footer.html.erb
<footer style="margin-top: 80px;" class="row">
			<div class="container-fluid padd">
				<div class="row">
					<section class="col-xs-12 col-sm-6 col-md-4">						
						<h3 style="text-align:center;"><i class="fa fa-flag"></i> Etiquetas</h3>
					</section>
					<section class="hidden-xs col-xs-12 col-sm-6 col-md-4">						
						<h3 style="text-align:center;"><i class="fa fa-code"></i> Proyectos</h3>
					</section>
					<section class="hidden-xs hidden-sm col-md-4">						
						<h3 style="text-align:center;"><i class="fa fa-th-large"></i> Social</h3>
					</section>
				</div>
				<div class="row">
					<script>
						$(document).ready(function(){
							$("#categorias a").each(function(i){
								if(i%2!=0){$(this).addClass("fsPair");}
								else{$(this).addClass("fsNon");}
							});
						});	
					</script>

				<section id="categorias" class="row col-xs-12 col-sm-6 col-md-4">	
						<section class="col-xs-4 col-sm-3 col-md-4">					
							<ul class="visible-lg-inline-block visible-md-inline-block visible-sm-inline-block visible-xs-inline-block">
		    					<li><a class="fsNon" href="#">Node.js</a></li>
			    				<li><a class="fsPair" href="#">PHP5 it's the shit!</a></li>
			    				<li><a class="fsNon" href="#">ZanPHP</a></li>
			    				<li><a class="fsPair" href="#">Rubi On Rails</a></li>
			    				<li><a class="fsNon" href="#">Kendall Jenner</a></li>
			    				<li><a class="fsPair" href="#">SQL</a></li>
			    				<li><a class="fsNon" href="#">C++</a></li>
			    				<li><a class="fsPair" href="#">MySql</a></li>
			    				<li><a class="fsNon" href="#">PhPMyAdmin</a></li>
			    			</ul>
			    		</section>
						<section class="col-xs-4 col-sm-3 col-md-4">					
			    			<ul class="visible-lg-inline-block visible-md-inline-block visible-sm-inline-block visible-xs-inline-block">
			    				<li><a class="fsPair" href="#">Javascript</a></li>
			    				<li><a class="fsNon" href="#">Ubuntu</a></li>
			    				<li><a class="fsPair" href="#">Jessica Nigri</a></li>
			    				<li><a class="fsNon" href="#">Phyton</a></li>
			    				<li><a class="fsPair" href="#">Linux</a></li>
			    				<li><a class="fsNon" href="#">C#</a></li>
			    				<li><a class="fsPair" href="#">PHP5</a></li>
			    				<li><a class="fsNon" href="#">jQuery</a></li>
			    				<li><a class="fsPair" href="#">Android</a></li>
			    			</ul>
			    		</section>
			    		<section class="col-xs-4 col-sm-3 col-md-4">					
			    			<ul class="visible-lg-inline-block visible-md-inline-block visible-sm-inline-block visible-xs-inline-block">
			    				<li><a class="fsNon" href="#">Andy Bros</a></li>
			    				<li><a class="fsPair" href="#">Testing</a></li>
			    				<li><a class="fsNon" href="#">Codeigniter</a></li>
			    				<li><a class="fsPair" href="#">JAVA</a></li>
			    				<li><a class="fsNon" href="#">GTAV</a></li>
			    				<li><a class="fsPair" href="#">IOS</a></li>
			    				<li><a class="fsNon" href="#">Games</a></li>
			    				<li><a class="fsPair" href="#">Kendall Jenner</a></li>
			    				<li><a class="fsNon" href="#">HHI 2013</a></li>
			    			</ul>
			    		</section>
					</section>

					<section id="last-projects" class="hidden-xs row col-xs-12 col-sm-6 col-md-4">
						<ul>
							<div class="row">
								<div class="col-sm-3 col-md-4">
									<li><%= image_tag "kciaad.png", :alt => "chahci", :title => "chahci", :class => "img-circle img-responsive" %></li>
								</div>
								<div class="col-sm-3 col-md-4">
									<li><%= image_tag "kj.png", :alt => "chahci", :title => "chahci", :class => "img-circle img-responsive" %></li>
								</div>
								<div class="col-sm-3 col-md-4">
									<li><%= image_tag "mgsv.png", :alt => "chahci", :title => "chahci", :class => "img-circle img-responsive" %></li>
								</div>
							</div>
						</ul>
						<ul>
							<div class="row">
								<div class="col-sm-3 col-md-4">
									<li><%= image_tag "kciaad.png", :alt => "chahci", :title => "chahci", :class => "img-circle img-responsive" %></li>
								</div>
								<div class="col-sm-3 col-md-4">
									<li><%= image_tag "kj.png", :alt => "chahci", :title => "chahci", :class => "img-circle img-responsive" %></li>
								</div>
								<div class="col-sm-3 col-md-4">
									<li><%= image_tag "mgsv.png", :alt => "chahci", :title => "chahci", :class => "img-circle img-responsive" %></li>
								</div>
							</div>
						</ul>
					</section>

					<section class="hidden-xs hidden-sm row col-xs-12 col-sm-12 col-md-4">
					<a href="https://twitter.com/RubinMz_" class="twitter-follow-button" data-show-count="false">Follow @RubinMz_</a>
					
					<div class="btn-toolbar">
						<div class="btn-group btn-group-sm">
							<button class="btn btn-default"><span class="glyphicon glyphicon-envelope"></span></button>
							<button class="btn btn-default"><span class="glyphicon glyphicon-thumbs-up"></span></button>
							<button class="btn btn-default"><span class="glyphicon glyphicon-share-alt"></span></button>
							<button class="btn btn-default"><span class="glyphicon glyphicon-home"></span></button>
						</div>
					</div>
					<div class="btn-toolbar">
						<div class="btn-group">
							<button class="btn btn-social-icon btn-twitter">
							    <i class="fa fa-twitter"></i>
							  </button>
							<button class="btn btn-default">2</button>
							<button class="btn btn-default">3</button>
							<button class="btn btn-default">3</button>
						</div>
					</div>
					</section>
				</div>

				<div class="row visible-xs">
					<section class="col-md-12">						
						<h3 style="text-align:center;"><i class="fa fa-flag"></i> Proyectos</h3>
					</section>
				</div>

				<div class="row">
					<section class="visible-xs row col-xs-12 col-sm-6 col-md-4">
						<ul style=" list-style-type:none;">
							<li><%= image_tag "mgsv.png", :alt => "chachi", :title => "chachi", :style => "width:150px; padding:5px;", :class => "img-circle img-responsive" %></li>
							<li><%= image_tag "kj.png", :alt => "chachi", :title => "chachi", :style => "width:150px; padding:5px;", :class => "img-circle img-responsive" %></li>
							<li><%= image_tag "mgsv.png", :alt => "chachi", :title => "chachi", :style => "width:150px; padding:5px;", :class => "img-circle img-responsive" %></li>
						</ul>
					</section>
				</div>

				<div class="row visible-xs visible-sm">
					<section class="col-md-12">						
						<h3 style="text-align:center;"><i class="fa fa-flag"></i> Social Network</h3>
					</section>
				</div>

			</div>

			<div class="row container-fluid blk-footer" style="margin-bottom:0;padding-bottom:0;">
				<section class="row col-xs-12 col-sm-7 col-md-8">
					<h4>Copyright 2015 RubinMz.com <small>Codebots.net</small></h4>
				</section>
				<section class="row col-xs-12 col-sm-5 col-md-4">
				<ul class="pull-right social-footer">
    				<li><a href="http://facebook.com/codebots.net" target="blank">
    				<span class="fa-stack fa-md">
					  <i class="fa fa-square-o fa-stack-2x"></i>
    				  <i class='fa fa-facebook fa-stack-1x'></i>
					</span>
    				</a></li>
    				<li><a href="http://twitter.com/RubinMz_" target="blank">
    				<span class="fa-stack fa-md">
					  <i class="fa fa-square-o fa-stack-2x"></i>
					  <i class="fa fa-twitter fa-stack-1x"></i>
					</span>
    				</a></li>
    				<li><a href="https://plus.google.com/u/0/117961280002960161413/posts" target="blank">
    				<span class="fa-stack fa-md">
					  <i class="fa fa-square-o fa-stack-2x"></i>
					  <i class="fa fa-google-plus fa-stack-1x"></i>
					</span>
    				</a></li>
    				<li><a href="https://instagram.com/rubinmz_/" target="blank">
    				<span class="fa-stack fa-md">
					  <i class="fa fa-square-o fa-stack-2x"></i>
					  <i class="fa fa-instagram fa-stack-1x"></i>
					</span>
    				</a></li>
    				<li><a href="https://www.tumblr.com/blog/rubinmz" target="blank">
    				<span class="fa-stack fa-md">
					  <i class="fa fa-square-o fa-stack-2x"></i>
					  <i class="fa fa-tumblr fa-stack-1x"></i>
					</span>
    				</a></li>
    				<li><a href="https://www.youtube.com/channel/UCHRFygUalRp-uwyBhLJkJDg" target="blank">
    				<span class="fa-stack fa-md">
					  <i class="fa fa-square-o fa-stack-2x"></i>
					  <i class="fa fa-youtube fa-stack-1x"></i>
					</span>
    				</a></li>
    				<li><a href="https://github.com/rubinmz" target="blank">
    				<span class="fa-stack fa-md">
					  <i class="fa fa-square-o fa-stack-2x"></i>
					  <i class="fa fa-github fa-stack-1x"></i>
					</span>
    				</a></li>
    				<li><a href="#">
    				<span class="fa-stack fa-md">
					  <i class="fa fa-square-o fa-stack-2x"></i>
					  <i class="fa fa-linkedin fa-stack-1x"></i>
					</span>
    				</a></li>
    			</ul>
		</footer>

app/views/layouts/_messagesLayout.html.erb
<% if flash[:notice]%>
	<div class="alert alert-info alert-dismissable">
		<button type="button" class="close" data-dismiss="alert" aria-hidden="true" ><i class="fa fa-times"></i>x</button>
		<%= flash[:notice]%>
	</div>
<% end %>

<% if flash[:alert]%>
	<div class="alert alert-danger alert-dismissable">
		<button type="button" class="close" data-dismiss="alert" aria-hidden="true" ><i class="fa fa-times"></i>x</button>
		<%= flash[:alert]%>
	</div>
<% end %>

<!-- esta madre no sirvio con ayuda del application_helper... revisar por qué....

!% flash.each do | type, message| %>
	<div class="alert <!%= flash_class type %> alert-dismissable">
    	 <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
    	 <!%= message %>
	</div>
<!% end %-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" class="no-js">
	<head>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge"> 
		<meta name="viewport" content="width=device-width, user-scalable=no initial-scale=1"> 
		<title>Codebots.net</title>
		<meta name="description" content="Website to show a few tutorials about web programming and learn the new stuff in this world." />
		<meta name="keywords" content="codebots.net, codebots, net, rubinmz, programming, ruby, css3 java, html5, javascript, jquery, rubyonrails" />
		<meta name="author" content="Codebots" />
		<%= favicon_link_tag 'rubyicon.ico' %>
		<!-- custom scrollbar stylesheet -->
	<!--link rel="stylesheet" href="css/jquery.mCustomScrollbar.css"-->
	
	<!-- demo CSS -->
	<style>
		html, body{ height: 100%; }
	</style>
	</head>
<body>
	<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');
	</script>

<header>
			<nav class="navbar navbar-default navbar-fixed-top navbar-inverse">
				<div class="container-fluid">
					<div class="navbar-header">

						<%= link_to root_path, :class => "navbar-brand" do%>
							<%= image_tag "duscae.png", :alt => "Codebots.net", :title => "Codebots.net", :style => "width:70px;padding-top:0; margin-top:-15px;" %>
					    <% end %>
						<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-1">
							<span class="sr-only">Menu</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
						
						<%= link_to root_path, :class => "navbar-brand" do%>
							Rubin <small>Mz</small>
						<% end %>
					</div>
					
					<div class="collapse navbar-collapse" id="navbar-1">
						<ul class="nav navbar-nav">



							<li class="active"><%= link_to "Inicio", root_path%></li>
							<li class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">
									Tutoriales <span class="caret"></span>
								</a>
								<ul class="dropdown-menu">
									<li><a href="#">Ruby</a></li>
									<li><a href="#">Java</a></li>
									<li class="divider"><a href="#"></a></li>
									<li><a href="#">HTML</a></li>
									<li><a href="#">CSS</a></li>
									<li><a href="#">Javascript</a></li>
								</ul>
							</li>
							<li><%= link_to "Acerca", acerca_path%></li>
							<li><a href="#">Descargas</a></li>
							<li><%= link_to "Foro", foro_path%></li>
						</ul>
						
						<form action="" class="navbar-form pull-left hidden-xs hidden-sm" role="search">
							<div class="form-group">
								<input type="text" class="form-control" placeholder="Buscar" />
							</div>
						</form>

						<form action="" class="navbar-form navbar-left visible-xs" role="search">
							<div class="form-group">
								<input type="text" class="form-control" placeholder="Buscar" />
							</div>
						</form>

						
						<ul class="nav navbar-nav navbar-right pull-right hidden-xs">

						<% if user_signed_in? %>
								<li class="dropdown">
									<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">
											<i class="fa fa-user fa-fw"></i> <%= current_user.name %>
									</a>
									<ul class="dropdown-menu">
										<li>
											<%= link_to edit_user_registration_path do %>
												<i class="fa fa-cog"></i> Editar cuenta
											<% end %> 
										</li>
										<li>
											<%= link_to home_path current_user do %>
												<i class="fa fa-diamond"></i> Mis Posts
											<% end %> 
										</li>
										<li class="divider"><a href="#"></a></li>
										<li>
										<%= link_to destroy_user_session_path, :method => :delete  do %>
											<i class="fa fa-sign-out"></i> Cerrar sesión
										<% end %> 
										</li>
									</ul>
								</li>
						<% else %>
								<li>
									<%= link_to new_user_session_path do %>
										<i class="fa fa-sign-in"></i> Login
									<% end %> 
								</li>	
						<% end %>
							<!--li><a href="#">Registro</a></li-->
						</ul>

						<ul class="nav navbar-nav navbar-right visible-xs">
						<% if user_signed_in? %>
								<li class="dropdown">
									<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">
											<i class="fa fa-user fa-fw"></i> <%= current_user.name %>
									</a>
									<ul class="dropdown-menu">
										<li>
											<%= link_to edit_user_registration_path do %>
												<i class="fa fa-cog"></i> Edita cuenta
											<% end %> 
										</li>
										<li>
											<%= link_to home_path  current_user do %>
												<i class="fa fa-diamond"></i> Mis Posts
											<% end %> 
										</li>
										<li class="divider"><a href="#"></a></li>
										<li>
										<%= link_to destroy_user_session_path, :method => :delete  do %>
											<i class="fa fa-sign-out"></i> Cerrar sesión
										<% end %> 
										</li>
									</ul>
								</li>			
						<% else %>
								<li>
									<%= link_to new_user_session_path do %>
										<i class="fa fa-sign-in"></i> Login
									<% end %> 
								</li>	
						<% end %>
							<!--li><a href="#">Registro</a></li-->
						</ul>

					</div>
			</nav>	
			
		</header>


<!--% flash.each do |name, msg|%>
	<!% = content_tag(: div, msg, c l a s s : " a l ert alert- # ( name ) " )%>
<!% en d % -->
<div class="container-fluid">
	<% if flash[:notice]%>
			<div class="alert alert-info alert-dismissable">
				<button type="button" class="close" data-dismiss="alert" aria-hidden="true" ><i class="fa fa-times"></i></button>
				<%= flash[:notice]%>
			</div>
		<% end %>

		<% if flash[:alert]%>
			<div class="alert alert-danger alert-dismissable">
				<button type="button" class="close" data-dismiss="alert" aria-hidden="true" ><i class="fa fa-times"></i></button>
				<%= flash[:alert]%>
			</div>
		<% end %>

	<%= yield %>

	
</div>
	<%= render "layouts/footer"%>
	

<!-- custom scrollbar plugin -->
			<!--script>
			(function($){
				$(window).ready(function(){					
					$("body").mCustomScrollbar({
						theme:"minimal-dark"
					});
				});
			})
			(jQuery);
		</script-->

</body>
</html>

app/views/pins/edit.html.erb
<h1>Editar Recurso</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @pin %> |
<%= link_to 'Regresar', pins_path %>

app/views/pins/index.html.erb
<div class="row">
		<div class="container-fluid">			 
			 <%= link_to new_pin_path do %>
				<h4 class="well"><i class="fa fa-plus-circle"></i> Nuevo Recurso</h4>
  			 <% end %> 

			
			<section class="row col-xs-offset-2 col-md-offset-0 col-sm-offset-0 col-xs-8 col-sm-12 col-md-8">
				<br/>

				<div class="row">
					<section class="col-xs-12 col-sm-12 col-md-12">
					   	<%= render @pins %>
					</section>
				</div>
				<br/>
				<p><%= will_paginate @pins %></p>
			</section>				
			<%= render "layouts/aside"%>
		</div>
</div>

app/views/pins/new.html.erb
<h1>Nuevo Recurso</h1>

<%= render 'form' %>

<%= link_to 'Regresar', pins_path %>

app/views/pins/show.html.erb
<div class="row span6 offset3 well">
	<% if @pin.image? %>
	<div class="col-md-6">
		<%= image_tag @pin.image , :class=> "image-post img-responsive" %>		
	</div>
	<div class="col-md-6">
		<strong>Título:</strong>
  		<h2 class="post-title"><%= @pin.description %></h2>
	</div>
  
  <p>Fecha de creación:</p>
  <%= @pin.created_at %><br/>
  <code>Creado por 
  	<%= @pin.user.name %>
  </code>
  <% else %>
  	<div class="col-md-12">
		<strong>Título:</strong>
  		<h2 class="post-title"><%= @pin.description %></h2>
	</div>
  
  <p>Fecha de creación:</p>
  <%= "Hace " + time_ago_in_words(@pin.created_at) %><br/>
  <%= @pin.created_at %><br/>
  <code>Creado por 
  	<%= @pin.user.name %>
  </code>
  <% end %>

</div>

<div class="row span9 ">
<% if current_user == @pin.user %>
	<%= link_to 'Editar', edit_pin_path(@pin) %> |
<% end %>
	<%= link_to 'Regresar', pins_path %>
</div>